// ============================================================
// EIS Object Catalog — All placeable world objects
// ============================================================

import type { WorldObject, ObjectType } from './world-map-types';

type CatalogEntry = Omit<WorldObject, 'id' | 'x' | 'y' | 'currentUsers' | 'lastUsedTick'>;

export const OBJECT_CATALOG: Record<ObjectType, CatalogEntry> = {
  // ---- Resource Nodes ----
  well: {
    name: 'Well',
    type: 'well',
    category: 'water',
    icon: '\u{1FAA3}',
    color: '#3B82F6',
    interactions: [
      { name: 'Drink', duration: 2, needsAffected: { thirst: -40 } },
      { name: 'Fill Container', duration: 3, needsAffected: { thirst: -10 }, itemsProduced: { water_flask: 1 } },
    ],
    satisfiesNeed: 'thirst',
    needSatisfactionAmount: 40,
    capacity: 3,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  spring: {
    name: 'Natural Spring',
    type: 'spring',
    category: 'water',
    icon: '\u{1F4A7}',
    color: '#60A5FA',
    interactions: [
      { name: 'Drink', duration: 1, needsAffected: { thirst: -50 } },
    ],
    satisfiesNeed: 'thirst',
    needSatisfactionAmount: 50,
    capacity: 5,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  berry_bush: {
    name: 'Berry Bush',
    type: 'berry_bush',
    category: 'food',
    icon: '\u{1FAD0}',
    color: '#DC2626',
    interactions: [
      { name: 'Pick Berries', duration: 2, needsAffected: { hunger: -20 }, itemsProduced: { berries: 3 } },
      { name: 'Eat Berries', duration: 1, needsAffected: { hunger: -25 } },
    ],
    satisfiesNeed: 'hunger',
    needSatisfactionAmount: 25,
    capacity: 2,
    cooldownTicks: 8,
    durability: 80,
    isDestructible: true,
    lootTable: ['berries'],
  },
  apple_tree: {
    name: 'Apple Tree',
    type: 'apple_tree',
    category: 'food',
    icon: '\u{1F34E}',
    color: '#22C55E',
    interactions: [
      { name: 'Pick Apples', duration: 3, needsAffected: { hunger: -15 }, itemsProduced: { apple: 2 } },
      { name: 'Eat Apple', duration: 1, needsAffected: { hunger: -20 } },
    ],
    satisfiesNeed: 'hunger',
    needSatisfactionAmount: 20,
    capacity: 2,
    cooldownTicks: 12,
    durability: 100,
    isDestructible: false,
  },
  ore_vein: {
    name: 'Ore Vein',
    type: 'ore_vein',
    category: 'resource',
    icon: '\u{1FAA8}',
    color: '#92400E',
    interactions: [
      { name: 'Mine Ore', duration: 6, needsAffected: { energy: 15 }, itemsProduced: { raw_ore: 2 }, skillGain: { mining: 5 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 2,
    cooldownTicks: 4,
    durability: 100,
    isDestructible: true,
    lootTable: ['raw_ore'],
  },
  lumber_pile: {
    name: 'Lumber Pile',
    type: 'lumber_pile',
    category: 'resource',
    icon: '\u{1FAB5}',
    color: '#92400E',
    interactions: [
      { name: 'Chop Wood', duration: 4, needsAffected: { energy: 10 }, itemsProduced: { lumber: 3 }, skillGain: { woodcutting: 3 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 2,
    cooldownTicks: 2,
    durability: 80,
    isDestructible: true,
    lootTable: ['lumber'],
  },
  herb_patch: {
    name: 'Herb Patch',
    type: 'herb_patch',
    category: 'resource',
    icon: '\u{1F33F}',
    color: '#16A34A',
    interactions: [
      { name: 'Gather Herbs', duration: 3, needsAffected: {}, itemsProduced: { herbs: 2 }, skillGain: { herbalism: 4 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 2,
    cooldownTicks: 6,
    durability: 60,
    isDestructible: true,
    lootTable: ['herbs'],
  },

  // ---- Crafting Stations ----
  forge: {
    name: 'Forge',
    type: 'forge',
    category: 'crafting',
    icon: '\u{2692}',
    color: '#EF4444',
    interactions: [
      { name: 'Smith Weapon', duration: 8, needsAffected: { energy: 20 }, itemsRequired: { raw_ore: 2 }, itemsProduced: { iron_weapon: 1 }, skillGain: { smithing: 8 } },
      { name: 'Smith Armor', duration: 10, needsAffected: { energy: 25 }, itemsRequired: { raw_ore: 3 }, itemsProduced: { iron_armor: 1 }, skillGain: { smithing: 10 } },
    ],
    needSatisfactionAmount: 0,
    requiredSkill: 'smithing',
    capacity: 1,
    cooldownTicks: 2,
    durability: 100,
    isDestructible: false,
  },
  workbench: {
    name: 'Workbench',
    type: 'workbench',
    category: 'crafting',
    icon: '\u{1F6E0}',
    color: '#A16207',
    interactions: [
      { name: 'Craft Item', duration: 5, needsAffected: { energy: 10 }, itemsRequired: { lumber: 2 }, itemsProduced: { wooden_item: 1 }, skillGain: { crafting: 5 } },
      { name: 'Repair Equipment', duration: 4, needsAffected: { energy: 8 }, skillGain: { crafting: 3 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 1,
    durability: 90,
    isDestructible: true,
  },
  cooking_fire: {
    name: 'Cooking Fire',
    type: 'cooking_fire',
    category: 'food',
    icon: '\u{1F525}',
    color: '#F59E0B',
    interactions: [
      { name: 'Cook Meal', duration: 4, needsAffected: { hunger: -50 }, itemsRequired: { raw_meat: 1 }, itemsProduced: { cooked_meal: 1 }, skillGain: { cooking: 5 } },
      { name: 'Warm Up', duration: 2, needsAffected: { comfort: -15 } },
      { name: 'Boil Water', duration: 3, needsAffected: { thirst: -30 }, skillGain: { cooking: 2 } },
    ],
    satisfiesNeed: 'hunger',
    needSatisfactionAmount: 50,
    capacity: 4,
    cooldownTicks: 1,
    durability: 60,
    isDestructible: true,
  },
  alchemy_table: {
    name: 'Alchemy Table',
    type: 'alchemy_table',
    category: 'crafting',
    icon: '\u{2697}',
    color: '#7C3AED',
    interactions: [
      { name: 'Brew Potion', duration: 6, needsAffected: {}, itemsRequired: { herbs: 2 }, itemsProduced: { potion: 1 }, skillGain: { alchemy: 6 } },
      { name: 'Study Ingredients', duration: 3, needsAffected: { selfActualization: -10 }, skillGain: { alchemy: 3 } },
    ],
    needSatisfactionAmount: 0,
    requiredSkill: 'alchemy',
    capacity: 1,
    cooldownTicks: 2,
    durability: 80,
    isDestructible: true,
  },
  loom: {
    name: 'Loom',
    type: 'loom',
    category: 'crafting',
    icon: '\u{1F9F5}',
    color: '#C084FC',
    interactions: [
      { name: 'Weave Cloth', duration: 5, needsAffected: { energy: 8 }, itemsProduced: { cloth: 1 }, skillGain: { weaving: 4 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 1,
    durability: 70,
    isDestructible: true,
  },
  tanning_rack: {
    name: 'Tanning Rack',
    type: 'tanning_rack',
    category: 'crafting',
    icon: '\u{1F9F6}',
    color: '#92400E',
    interactions: [
      { name: 'Tan Hide', duration: 6, needsAffected: { energy: 12 }, itemsRequired: { raw_hide: 1 }, itemsProduced: { leather: 1 }, skillGain: { leatherworking: 5 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 3,
    durability: 75,
    isDestructible: true,
  },

  // ---- Social ----
  campfire: {
    name: 'Campfire',
    type: 'campfire',
    category: 'social',
    icon: '\u{1F3D5}',
    color: '#F97316',
    interactions: [
      { name: 'Socialize', duration: 4, needsAffected: { socialInteraction: -30, comfort: -10 } },
      { name: 'Tell Stories', duration: 6, needsAffected: { socialInteraction: -40, entertainment: -20 }, skillGain: { charisma: 3 } },
      { name: 'Warm Up', duration: 2, needsAffected: { comfort: -15 } },
    ],
    satisfiesNeed: 'socialInteraction',
    needSatisfactionAmount: 30,
    capacity: 8,
    cooldownTicks: 0,
    durability: 40,
    isDestructible: true,
  },
  bench: {
    name: 'Bench',
    type: 'bench',
    category: 'social',
    icon: '\u{1FA91}',
    color: '#78716C',
    interactions: [
      { name: 'Sit and Rest', duration: 2, needsAffected: { rest: -10, comfort: -5 } },
      { name: 'Chat', duration: 3, needsAffected: { socialInteraction: -15 } },
    ],
    satisfiesNeed: 'rest',
    needSatisfactionAmount: 10,
    capacity: 3,
    cooldownTicks: 0,
    durability: 80,
    isDestructible: true,
  },
  tavern_table: {
    name: 'Tavern Table',
    type: 'tavern_table',
    category: 'social',
    icon: '\u{1F37B}',
    color: '#A16207',
    interactions: [
      { name: 'Drink', duration: 3, needsAffected: { thirst: -20, socialInteraction: -15, entertainment: -10 } },
      { name: 'Eat Meal', duration: 4, needsAffected: { hunger: -35, socialInteraction: -10 } },
      { name: 'Gamble', duration: 5, needsAffected: { entertainment: -25 }, skillGain: { perception: 2 } },
    ],
    satisfiesNeed: 'socialInteraction',
    needSatisfactionAmount: 15,
    capacity: 4,
    cooldownTicks: 0,
    durability: 90,
    isDestructible: true,
  },
  market_stall: {
    name: 'Market Stall',
    type: 'market_stall',
    category: 'trade',
    icon: '\u{1F6D2}',
    color: '#2563EB',
    interactions: [
      { name: 'Trade', duration: 3, needsAffected: { socialInteraction: -10 }, skillGain: { trading: 4 } },
      { name: 'Browse Goods', duration: 2, needsAffected: { entertainment: -5 } },
    ],
    satisfiesNeed: 'socialInteraction',
    needSatisfactionAmount: 10,
    capacity: 2,
    cooldownTicks: 1,
    durability: 70,
    isDestructible: true,
  },
  notice_board: {
    name: 'Notice Board',
    type: 'notice_board',
    category: 'social',
    icon: '\u{1F4CB}',
    color: '#A16207',
    interactions: [
      { name: 'Read Notices', duration: 2, needsAffected: { selfActualization: -5 } },
      { name: 'Post Notice', duration: 1, needsAffected: {} },
    ],
    needSatisfactionAmount: 0,
    capacity: 3,
    cooldownTicks: 0,
    durability: 60,
    isDestructible: true,
  },
  stage: {
    name: 'Stage',
    type: 'stage',
    category: 'social',
    icon: '\u{1F3AD}',
    color: '#DC2626',
    interactions: [
      { name: 'Perform', duration: 6, needsAffected: { entertainment: -30, socialInteraction: -20 }, skillGain: { charisma: 5 } },
      { name: 'Watch Performance', duration: 4, needsAffected: { entertainment: -25, socialInteraction: -10 } },
    ],
    satisfiesNeed: 'entertainment',
    needSatisfactionAmount: 25,
    capacity: 1,
    cooldownTicks: 4,
    durability: 80,
    isDestructible: true,
  },

  // ---- Rest ----
  bed: {
    name: 'Bed',
    type: 'bed',
    category: 'rest',
    icon: '\u{1F6CF}',
    color: '#6366F1',
    interactions: [
      { name: 'Sleep', duration: 8, needsAffected: { rest: -80, energy: -40, comfort: -20 } },
      { name: 'Nap', duration: 3, needsAffected: { rest: -30, energy: -15 } },
    ],
    satisfiesNeed: 'rest',
    needSatisfactionAmount: 80,
    capacity: 1,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  hammock: {
    name: 'Hammock',
    type: 'hammock',
    category: 'rest',
    icon: '\u{1F3DD}',
    color: '#2DD4BF',
    interactions: [
      { name: 'Rest', duration: 4, needsAffected: { rest: -40, comfort: -15 } },
    ],
    satisfiesNeed: 'rest',
    needSatisfactionAmount: 40,
    capacity: 1,
    cooldownTicks: 0,
    durability: 50,
    isDestructible: true,
  },
  tent: {
    name: 'Tent',
    type: 'tent',
    category: 'rest',
    icon: '\u{26FA}',
    color: '#A3A3A3',
    interactions: [
      { name: 'Sleep', duration: 6, needsAffected: { rest: -60, energy: -30, safety: -10 } },
      { name: 'Shelter', duration: 2, needsAffected: { comfort: -10, safety: -5 } },
    ],
    satisfiesNeed: 'rest',
    needSatisfactionAmount: 60,
    capacity: 2,
    cooldownTicks: 0,
    durability: 40,
    isDestructible: true,
  },
  sleeping_bag: {
    name: 'Sleeping Bag',
    type: 'sleeping_bag',
    category: 'rest',
    icon: '\u{1F9F7}',
    color: '#0EA5E9',
    interactions: [
      { name: 'Sleep', duration: 5, needsAffected: { rest: -45, energy: -20 } },
    ],
    satisfiesNeed: 'rest',
    needSatisfactionAmount: 45,
    capacity: 1,
    cooldownTicks: 0,
    durability: 30,
    isDestructible: true,
  },

  // ---- Training ----
  training_dummy: {
    name: 'Training Dummy',
    type: 'training_dummy',
    category: 'training',
    icon: '\u{1F93A}',
    color: '#A16207',
    interactions: [
      { name: 'Practice Combat', duration: 5, needsAffected: { energy: 15, selfActualization: -10 }, skillGain: { combat: 6 } },
    ],
    satisfiesNeed: 'selfActualization',
    needSatisfactionAmount: 10,
    capacity: 1,
    cooldownTicks: 1,
    durability: 60,
    isDestructible: true,
  },
  archery_target: {
    name: 'Archery Target',
    type: 'archery_target',
    category: 'training',
    icon: '\u{1F3AF}',
    color: '#DC2626',
    interactions: [
      { name: 'Practice Archery', duration: 4, needsAffected: { energy: 10, selfActualization: -10 }, skillGain: { archery: 5 } },
    ],
    satisfiesNeed: 'selfActualization',
    needSatisfactionAmount: 10,
    capacity: 2,
    cooldownTicks: 0,
    durability: 50,
    isDestructible: true,
  },
  sparring_ring: {
    name: 'Sparring Ring',
    type: 'sparring_ring',
    category: 'training',
    icon: '\u{1F94A}',
    color: '#EAB308',
    interactions: [
      { name: 'Spar', duration: 6, needsAffected: { energy: 20, socialInteraction: -15, selfActualization: -15 }, skillGain: { combat: 8 } },
    ],
    satisfiesNeed: 'selfActualization',
    needSatisfactionAmount: 15,
    capacity: 2,
    cooldownTicks: 2,
    durability: 100,
    isDestructible: false,
  },
  library_shelf: {
    name: 'Library Shelf',
    type: 'library_shelf',
    category: 'training',
    icon: '\u{1F4DA}',
    color: '#7C3AED',
    interactions: [
      { name: 'Study', duration: 5, needsAffected: { selfActualization: -20, entertainment: -5 }, skillGain: { knowledge: 6 } },
      { name: 'Read for Pleasure', duration: 3, needsAffected: { entertainment: -15, rest: -5 } },
    ],
    satisfiesNeed: 'selfActualization',
    needSatisfactionAmount: 20,
    capacity: 3,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },

  // ---- Defense ----
  wall_segment: {
    name: 'Wall Segment',
    type: 'wall_segment',
    category: 'defense',
    icon: '\u{1F9F1}',
    color: '#78716C',
    interactions: [
      { name: 'Repair', duration: 4, needsAffected: { energy: 10 }, itemsRequired: { lumber: 1 }, skillGain: { crafting: 2 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: true,
  },
  gate: {
    name: 'Gate',
    type: 'gate',
    category: 'defense',
    icon: '\u{1F6AA}',
    color: '#92400E',
    interactions: [
      { name: 'Open/Close', duration: 1, needsAffected: {} },
      { name: 'Guard', duration: 6, needsAffected: { safety: -15, energy: 10 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 2,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: true,
  },
  watchtower_obj: {
    name: 'Watchtower',
    type: 'watchtower_obj',
    category: 'defense',
    icon: '\u{1F3F0}',
    color: '#6B7280',
    interactions: [
      { name: 'Stand Watch', duration: 6, needsAffected: { safety: -20, energy: 10 }, skillGain: { perception: 4 } },
      { name: 'Scout', duration: 3, needsAffected: { safety: -10 }, skillGain: { perception: 2 } },
    ],
    satisfiesNeed: 'safety',
    needSatisfactionAmount: 20,
    requiredRole: 'Guard',
    capacity: 1,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  barricade: {
    name: 'Barricade',
    type: 'barricade',
    category: 'defense',
    icon: '\u{1F6A7}',
    color: '#F59E0B',
    interactions: [
      { name: 'Reinforce', duration: 3, needsAffected: { energy: 8 }, itemsRequired: { lumber: 1 }, skillGain: { crafting: 2 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 0,
    durability: 50,
    isDestructible: true,
  },
  trap: {
    name: 'Trap',
    type: 'trap',
    category: 'defense',
    icon: '\u{1FAA4}',
    color: '#EF4444',
    interactions: [
      { name: 'Set Trap', duration: 3, needsAffected: {}, skillGain: { trapping: 4 } },
      { name: 'Disarm', duration: 2, needsAffected: {}, skillGain: { trapping: 2 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 0,
    durability: 30,
    isDestructible: true,
  },

  // ---- Storage ----
  chest: {
    name: 'Chest',
    type: 'chest',
    category: 'storage',
    icon: '\u{1F4E6}',
    color: '#A16207',
    interactions: [
      { name: 'Store Items', duration: 1, needsAffected: {} },
      { name: 'Retrieve Items', duration: 1, needsAffected: {} },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 0,
    durability: 80,
    isDestructible: true,
    lootTable: ['misc_items'],
  },
  barrel: {
    name: 'Barrel',
    type: 'barrel',
    category: 'storage',
    icon: '\u{1F6E2}',
    color: '#92400E',
    interactions: [
      { name: 'Store Liquids', duration: 1, needsAffected: {} },
      { name: 'Retrieve', duration: 1, needsAffected: {} },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 0,
    durability: 60,
    isDestructible: true,
  },
  crate: {
    name: 'Crate',
    type: 'crate',
    category: 'storage',
    icon: '\u{1F4E6}',
    color: '#78716C',
    interactions: [
      { name: 'Store', duration: 1, needsAffected: {} },
      { name: 'Retrieve', duration: 1, needsAffected: {} },
    ],
    needSatisfactionAmount: 0,
    capacity: 1,
    cooldownTicks: 0,
    durability: 50,
    isDestructible: true,
  },
  warehouse: {
    name: 'Warehouse',
    type: 'warehouse',
    category: 'storage',
    icon: '\u{1F3ED}',
    color: '#6B7280',
    interactions: [
      { name: 'Store Bulk', duration: 2, needsAffected: {} },
      { name: 'Retrieve Bulk', duration: 2, needsAffected: {} },
    ],
    needSatisfactionAmount: 0,
    capacity: 3,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  granary: {
    name: 'Granary',
    type: 'granary',
    category: 'storage',
    icon: '\u{1F33E}',
    color: '#CA8A04',
    interactions: [
      { name: 'Store Grain', duration: 2, needsAffected: {} },
      { name: 'Retrieve Grain', duration: 2, needsAffected: {}, itemsProduced: { grain: 5 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 2,
    cooldownTicks: 0,
    durability: 90,
    isDestructible: false,
  },

  // ---- Buildings ----
  house: {
    name: 'House',
    type: 'house',
    category: 'rest',
    icon: '\u{1F3E0}',
    color: '#A16207',
    interactions: [
      { name: 'Enter Home', duration: 1, needsAffected: { comfort: -10, safety: -10 } },
      { name: 'Sleep', duration: 8, needsAffected: { rest: -80, energy: -40, comfort: -20, safety: -10 } },
    ],
    satisfiesNeed: 'rest',
    needSatisfactionAmount: 80,
    capacity: 4,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  shop: {
    name: 'Shop',
    type: 'shop',
    category: 'trade',
    icon: '\u{1F3EA}',
    color: '#2563EB',
    interactions: [
      { name: 'Buy', duration: 2, needsAffected: {} },
      { name: 'Sell', duration: 2, needsAffected: {}, skillGain: { trading: 3 } },
      { name: 'Browse', duration: 1, needsAffected: { entertainment: -5 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 6,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  inn: {
    name: 'Inn',
    type: 'inn',
    category: 'social',
    icon: '\u{1F3E8}',
    color: '#CA8A04',
    interactions: [
      { name: 'Rent Room', duration: 1, needsAffected: { comfort: -5 } },
      { name: 'Eat at Inn', duration: 3, needsAffected: { hunger: -40, thirst: -20, socialInteraction: -10 } },
      { name: 'Socialize', duration: 4, needsAffected: { socialInteraction: -25, entertainment: -15 } },
    ],
    satisfiesNeed: 'socialInteraction',
    needSatisfactionAmount: 25,
    capacity: 10,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  temple: {
    name: 'Temple',
    type: 'temple',
    category: 'social',
    icon: '\u{26EA}',
    color: '#E2E8F0',
    interactions: [
      { name: 'Pray', duration: 4, needsAffected: { comfort: -15, selfActualization: -20 } },
      { name: 'Meditate', duration: 3, needsAffected: { rest: -10, selfActualization: -15 } },
      { name: 'Seek Healing', duration: 2, needsAffected: { hygiene: -10 } },
    ],
    satisfiesNeed: 'selfActualization',
    needSatisfactionAmount: 20,
    capacity: 8,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
  blacksmith: {
    name: 'Blacksmith',
    type: 'blacksmith',
    category: 'crafting',
    icon: '\u{2692}',
    color: '#78716C',
    interactions: [
      { name: 'Smith Item', duration: 8, needsAffected: { energy: 20 }, itemsRequired: { raw_ore: 2 }, itemsProduced: { metal_item: 1 }, skillGain: { smithing: 8 } },
      { name: 'Repair', duration: 4, needsAffected: { energy: 10 }, skillGain: { smithing: 3 } },
    ],
    needSatisfactionAmount: 0,
    capacity: 2,
    cooldownTicks: 2,
    durability: 100,
    isDestructible: false,
  },
  farm_building: {
    name: 'Farm Building',
    type: 'farm_building',
    category: 'food',
    icon: '\u{1F3E1}',
    color: '#65A30D',
    interactions: [
      { name: 'Harvest Crops', duration: 5, needsAffected: { energy: 12 }, itemsProduced: { grain: 3, vegetables: 2 }, skillGain: { farming: 5 } },
      { name: 'Feed Animals', duration: 3, needsAffected: { energy: 8 }, skillGain: { farming: 2 } },
    ],
    satisfiesNeed: 'hunger',
    needSatisfactionAmount: 0,
    capacity: 3,
    cooldownTicks: 4,
    durability: 80,
    isDestructible: false,
  },
  guard_post: {
    name: 'Guard Post',
    type: 'guard_post',
    category: 'defense',
    icon: '\u{1F6E1}',
    color: '#6B7280',
    interactions: [
      { name: 'Guard Duty', duration: 8, needsAffected: { safety: -25, energy: 15 }, skillGain: { combat: 3, perception: 2 } },
      { name: 'Rest Between Shifts', duration: 2, needsAffected: { rest: -10, energy: -5 } },
    ],
    satisfiesNeed: 'safety',
    needSatisfactionAmount: 25,
    requiredRole: 'Guard',
    capacity: 2,
    cooldownTicks: 0,
    durability: 100,
    isDestructible: false,
  },
};

/** Get all object types for a category */
export function getObjectsByCategory(category: string): ObjectType[] {
  return (Object.entries(OBJECT_CATALOG) as [ObjectType, CatalogEntry][])
    .filter(([, entry]) => entry.category === category)
    .map(([type]) => type);
}

/** Get all unique categories */
export function getCategories(): string[] {
  const cats = new Set<string>();
  for (const entry of Object.values(OBJECT_CATALOG)) {
    cats.add(entry.category);
  }
  return Array.from(cats);
}

/** Create a new world object from catalog */
export function createWorldObject(type: ObjectType, x: number, y: number, id: string): WorldObject {
  const template = OBJECT_CATALOG[type];
  return {
    ...template,
    id,
    x,
    y,
    currentUsers: [],
    lastUsedTick: 0,
  };
}
