/**
 * Shapes of Exports/TableManifest.json (WEB-001, generated by
 * Scripts/export_table_manifest.py in the EISCORE repo) — the contract this
 * server leans on everywhere. Field names mirror the JSON exactly.
 */

export type Classification =
  | 'authored'
  | 'generated'
  | 'generated_unverified'
  | 'legacy'
  | 'raw_read';

export interface ManifestColumnType {
  name: string;
  ue5_type: string;
  pipe_multi: boolean;
  semicolon_hazard: boolean;
}

export interface ManifestRowKey {
  column0: string;
  unique: boolean;
  rows_lost_on_import: number;
}

export interface ManifestFlagDetail {
  generator?: string;
  source?: string;
  [key: string]: unknown;
}

export interface ManifestForeignKey {
  column: string;
  target_table: string;
  target_prefix: string;
}

export interface ManifestTable {
  path: string;
  folder: string;
  stem: string;
  row_count: number;
  columns: string[];
  column_types: ManifestColumnType[];
  row_key: ManifestRowKey;
  classification: Classification;
  flags: Record<string, ManifestFlagDetail>;
  foreign_keys?: ManifestForeignKey[];
}

export interface ManifestSummary {
  total_tables: number;
  classification_counts: Record<string, number>;
  raw_read_flagged: number;
  generated_at_note?: string;
  [key: string]: unknown;
}

export interface TableManifest {
  summary: ManifestSummary;
  worldgen_reference?: unknown;
  tables: ManifestTable[];
}

/** Slim listing row for GET /api/tables. */
export interface TableListEntry {
  path: string;
  folder: string;
  stem: string;
  classification: Classification;
  flags: Record<string, ManifestFlagDetail>;
  row_count: number;
}

/** Table content as it travels over the wire. Rows are arrays aligned to
 * `columns` — object keys would silently merge duplicate/odd header names
 * (the corpus has a table whose column 0 is literally `---`). */
export interface TablePayload {
  columns: string[];
  rows: string[][];
}

export interface WriteRequestBody extends TablePayload {
  message?: string;
  validate?: boolean;
}

export interface GuardCheckResult {
  name: string;
  passed: boolean;
  detail?: unknown;
}

/**
 * WEB-005 — one validation finding, from either validation surface. Field
 * names mirror what the sources actually give:
 *   - the worldgen validator's JSON items are {severity, rule, table, column,
 *     row, detail}: rule -> code, its `detail` string -> message, `table` is a
 *     stem (e.g. "SpaceTypes") and stays a stem, null column/row are omitted.
 *     Its severity literal is "WARNING", normalized to WARN here.
 *   - table guards emit ERROR findings with row/column filled where the guard
 *     knows them (row = the column-0 key for collisions); structured extras
 *     (collision row numbers, densities, offending values) ride in `detail`.
 */
export type FindingSeverity = 'ERROR' | 'WARN' | 'INFO';
export type FindingSource = 'worldgen-validator' | 'table-guards';

export interface Finding {
  source: FindingSource;
  severity: FindingSeverity;
  code: string;
  table?: string;
  row?: string;
  column?: string;
  message: string;
  detail?: unknown;
}

export interface FindingSummaryCounts {
  ERROR: number;
  WARN: number;
  INFO: number;
}

/** POST /api/validate/worldgen response. exitCode 1 means the validator found
 * errors — a result, never an HTTP failure. */
export interface WorldgenValidationResult {
  ranAt: string;
  exitCode: number;
  findings: Finding[];
  summaryCounts: FindingSummaryCounts;
}

/** POST /api/validate/table response — dry-run hard-rule guards against the
 * file currently on disk. No process runs, so no exitCode. */
export interface TableGuardCheckResult {
  ranAt: string;
  path: string;
  findings: Finding[];
  summaryCounts: FindingSummaryCounts;
}

export interface WriteSuccess {
  success: true;
  commit: string;
  validationReport: unknown;
}

export interface WriteFailure {
  success: false;
  reason: string;
  detail?: unknown;
}

export type WriteResult = WriteSuccess | WriteFailure;

export interface ScriptRunResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

// ---------------------------------------------------------------------------
// WEB-006 — vocabulary editor over web-owned world-gen source fragments.
// ---------------------------------------------------------------------------

export interface WorldgenFragmentInfo {
  exists: boolean;
  /** Data-row count (header excluded); null when absent or unparseable. */
  rowCount: number | null;
}

export interface WorldgenSourceEntry {
  stem: string;
  base: WorldgenFragmentInfo & { path: string };
  fragments: {
    ext: WorldgenFragmentInfo;
    web: WorldgenFragmentInfo;
    patch: WorldgenFragmentInfo;
    webPatch: WorldgenFragmentInfo;
  };
}

export interface WorldgenSourcesResult {
  extDir: string;
  stems: WorldgenSourceEntry[];
}

/** One row of <Stem>.web.patch.csv (schema RowName,Column,Op,Value,Reason —
 * the same patch mechanism normalize's script-owned .patch.csv layer uses). */
export interface WorldgenPatch {
  rowName: string;
  column: string;
  op: string;
  value: string;
  reason: string;
}

export interface WorldgenBaseRow {
  rowName: string;
  displayName: string;
  owner: 'base' | 'ext';
}

/** Everything a picker for one FK column may legally offer. */
export interface WorldgenFkOptions {
  column: string;
  targetTable: string;
  targetPrefix: string;
  rowNames: string[];
  groupTokens: string[];
  /** Reference-blessed specials: SpaceTypes categories for adjacency columns,
   * movement modes for TraversalType. */
  extras: string[];
}

export interface WorldgenGroupToken {
  token: string;
  domain: string;
  members: string[];
}

export interface WorldgenWebResult {
  stem: string;
  columns: string[];
  columnTypes: ManifestColumnType[];
  baseRows: WorldgenBaseRow[];
  /** Full web-owned rows, aligned to `columns`. */
  webRows: string[][];
  webPatches: WorldgenPatch[];
  fks: ManifestForeignKey[];
  fkOptions: WorldgenFkOptions[];
  wildcards: string[];
  groupTokens: WorldgenGroupToken[];
  adjacencyCategoryColumns: string[];
  traversalMovementModes: string[];
}

export interface WorldgenPutBody {
  webRows?: string[][];
  webPatches?: WorldgenPatch[];
  message?: string;
}

export interface WorldgenPutSuccess {
  success: true;
  /** null when the edit set was byte-identical to HEAD (nothing to commit). */
  commit: string | null;
  normalizeOutput: string;
  findings: Finding[];
  summaryCounts: FindingSummaryCounts;
}

// ---------------------------------------------------------------------------
// WEB-007 — Brief Studio.
// ---------------------------------------------------------------------------

export interface BriefListEntry {
  name: string;
  mtime: string;
  /** The brief's `Location:` value ('' when absent/unparseable). */
  location: string;
  /** Line count of the leading `#` comment block (the design notes). */
  commentLines: number;
}

export interface BriefListResult {
  dir: string;
  briefs: BriefListEntry[];
}

/** One parsed key block, same semantics as location_brief.py parse_brief(). */
export interface BriefParsedEntry {
  key: string;
  values: string[];
  inline: boolean;
}

export interface BriefGetResult {
  name: string;
  raw: string;
  parsed: {
    comments: string[];
    entries: BriefParsedEntry[];
  };
}

/** One location_brief.py run. exitCode 1 = at least one BLOCKER — a result,
 * never an HTTP failure. `result` is the tool's --json report, passed through
 * faithfully. `failure` is set only when the tool could not run/report. */
export interface BriefCheckResult {
  ranAt: string;
  exitCode: number;
  verdict: string | null;
  result: unknown;
  failure?: string;
}

export type BriefCheckOutcome =
  | { ok: true; check: BriefCheckResult }
  | { ok: false; detail: string };

export interface BriefPutBody {
  raw?: string;
  message?: string;
}

export interface BriefPutSuccess {
  success: true;
  name: string;
  commit: string;
  /** Informational — a NOT BUILDABLE brief still commits (its gaps ARE the
   * environment-art backlog). */
  check: BriefCheckResult;
}

export type BriefPutResult = BriefPutSuccess | WriteFailure;

export interface WorldgenPutValidationFailure {
  success: false;
  reason: 'validation_errors';
  findings: Finding[];
  summaryCounts: FindingSummaryCounts;
}

export type WorldgenPutResult = WorldgenPutSuccess | WorldgenPutValidationFailure | WriteFailure;

// ---------------------------------------------------------------------------
// WEB-009 — DAM
// ---------------------------------------------------------------------------

/** The consumed set, parsed live from Scripts/location_brief.py (the only
 * copy, per WG-213/WG-215). Never hardcoded server-side. */
export interface DamConsumedPieceTypes {
  source: string;
  count: number;
  /** Distinct consumer keys (VERT/ASM/EXO today), sorted. */
  consumers: string[];
  /** piece type -> consumers that read it. */
  types: Record<string, string[]>;
}

export interface DamPieceTypeRow {
  name: string;
  consumed: boolean;
  consumers: string[];
  total: number;
  byStyle: Record<string, number>;
}

export interface DamStyleFallback {
  style: string;
  family: string;
  chain: string[];
}

export interface DamKitCoverage {
  ranAt: string;
  catalogPath: string;
  consumedSource: string;
  totalRows: number;
  /** Rows whose PieceType some consumer reads. */
  consumedRows: number;
  /** WG-218's number, computed live: rows no generator will ever place. */
  inertRows: number;
  inertPct: number;
  styles: string[];
  pieceTypes: DamPieceTypeRow[];
  fallbacks: DamStyleFallback[];
}

export interface DamPackEntry {
  name: string;
  cityStyle: string;
  onDisk: boolean;
}

export interface DamPackList {
  ranAt: string;
  exitCode: number;
  /** null when --list output resisted parsing — render `raw` instead. */
  packs: DamPackEntry[] | null;
  raw: string;
}

export interface DamMergeSummary {
  kitKept: number;
  kitNew: number;
  kitTotal: number;
  propKept: number;
  propNew: number;
  propTotal: number;
}

export interface DamDryRunResult {
  pack: string;
  ranAt: string;
  exitCode: number;
  /** The classification report, verbatim. */
  report: string;
  merge: DamMergeSummary | null;
}

export interface DamFallbackCheck {
  /** author_city_style_fallback.py --check: 0 ok, non-zero = stale/missing
   * family — surfaced, never auto-fixed. */
  exitCode: number;
  output: string;
}

export interface DamPackWriteResult {
  success: true;
  pack: string;
  /** null = idempotent (the pack was already registered byte-identically). */
  commit: string | null;
  note?: string;
  diffstat: string | null;
  report: string;
  fallbackCheck: DamFallbackCheck;
}
