/**
 * Shapes of Exports/TableManifest.json (WEB-001, generated by
 * Scripts/export_table_manifest.py in the EISCORE repo) — the contract this
 * server leans on everywhere. Field names mirror the JSON exactly.
 */

export type Classification =
  | 'authored'
  | 'generated'
  | 'generated_unverified'
  | 'legacy'
  | 'raw_read';

export interface ManifestColumnType {
  name: string;
  ue5_type: string;
  pipe_multi: boolean;
  semicolon_hazard: boolean;
}

export interface ManifestRowKey {
  column0: string;
  unique: boolean;
  rows_lost_on_import: number;
}

export interface ManifestFlagDetail {
  generator?: string;
  source?: string;
  [key: string]: unknown;
}

export interface ManifestForeignKey {
  column: string;
  target_table: string;
  target_prefix: string;
}

export interface ManifestTable {
  path: string;
  folder: string;
  stem: string;
  row_count: number;
  columns: string[];
  column_types: ManifestColumnType[];
  row_key: ManifestRowKey;
  classification: Classification;
  flags: Record<string, ManifestFlagDetail>;
  foreign_keys?: ManifestForeignKey[];
}

export interface ManifestSummary {
  total_tables: number;
  classification_counts: Record<string, number>;
  raw_read_flagged: number;
  generated_at_note?: string;
  [key: string]: unknown;
}

export interface TableManifest {
  summary: ManifestSummary;
  worldgen_reference?: unknown;
  tables: ManifestTable[];
}

/** Slim listing row for GET /api/tables. */
export interface TableListEntry {
  path: string;
  folder: string;
  stem: string;
  classification: Classification;
  flags: Record<string, ManifestFlagDetail>;
  row_count: number;
}

/** Table content as it travels over the wire. Rows are arrays aligned to
 * `columns` — object keys would silently merge duplicate/odd header names
 * (the corpus has a table whose column 0 is literally `---`). */
export interface TablePayload {
  columns: string[];
  rows: string[][];
}

export interface WriteRequestBody extends TablePayload {
  message?: string;
  validate?: boolean;
}

export interface GuardCheckResult {
  name: string;
  passed: boolean;
  detail?: unknown;
}

export interface WriteSuccess {
  success: true;
  commit: string;
  validationReport: unknown;
}

export interface WriteFailure {
  success: false;
  reason: string;
  detail?: unknown;
}

export type WriteResult = WriteSuccess | WriteFailure;

export interface ScriptRunResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}
